#!/bin/bash

# start: Launch the application and any extra required processes locally.
#

# Drop out if one of the commands fails
set -e

# Ensure we are working from the top of the project
cd "$(dirname "$0")/.."
echo "Change directory to: $(pwd)"

# Run update script to ensure everything is up to date
script/update

# Start the application
echo "==> Start the application…"
echo

cargo run
