#!/bin/bash

# test: Run test suite for project. Optionally run an individual test(s).
#

# Drop out if one of the commands fails
set -e

echo
echo "==> Start running tests at $(date "+%H:%M:%S")"
echo

# Work out path to script folder
script_path=$(dirname "$0")

# Check if arguments are passed allowing call to specific test(s).
if [[ -n $1 ]]
then
  cargo test "$@"
else
  # Run lint on bash scripts if not run for specific test(s)
  "$script_path/bin/check_scripts"

  echo
  echo "==> Start running cargo tests at $(date "+%H:%M:%S")"
  echo

  cargo test
fi

echo
echo "==> Tests finished at $(date "+%H:%M:%S")"
echo
